### ISSUE TITLE
Missing step in Windows install instructions

### ISSUE THREAD

**Issue by LaneRendell** [lillian-lemmer/hypatia#22]
https://github.com/lillian-lemmer/hypatia/wiki/Installation-Instructions#windows

Step 2 should be installing pygame.

**Comment by lillian-lemmer** [comment]
That's covered in step 3. I did notice, however, that I don't go over how to install the Hypatia package for Windows.

**Comment by lillian-lemmer** [comment]
Okay, this should be resolved, see: https://github.com/lillian-lemmer/hypatia/wiki/Installation-Instructions#3-download-a-file-and-enter-a-command

Does this resolve your issue?
