### ISSUE TITLE
Convince current PyPI Hypatia author to rename project

### ISSUE THREAD

**Issue by lillian-lemmer** [lillian-lemmer/hypatia#24]
Chris McDonough
chrism@plope.com
https://github.com/Pylons/hypatia

**Comment by ejmr** [comment]
For what it's worth, this is unnecessary in my opinion.  Pylons is a well-known web framework for Python.  It's hard for me to imagine a situation where I would be searching for game engines or web frameworks and end up at the "wrong" Hypatia.

**Comment by lillian-lemmer** [comment]
That is true. I just really selfishly wanna be able to tell people to `pip install hypatia`, ha, ha!

**Comment by ejmr** [comment]
>  I just really selfishly wanna be able to tell people to `pip install hypatia`

Heh.  I can sympathize.

> By the way, thank you for contributions!

Thanks, but I haven't contributed anything *yet* ;)

**Comment by lillian-lemmer** [comment]
Ha, ha, true, true, I appreciate the interest, nonetheless. :) I should probably close this issue for now. I've done what I can already to contact them. :)
