### ISSUE TITLE
Rename py.test to tests.

### ISSUE THREAD

**Issue by SanketDG** [lillian-lemmer/hypatia#29]
It says [here](http://pytest.org/latest/goodpractises.html#choosing-a-test-layout-import-rules), to use a `tests` folder. And also, you can use a class for each and every test for better debugging, as mentioned [here](http://pytest.org/latest/getting-started.html#grouping-multiple-tests-in-a-class)

**Comment by lillian-lemmer** [comment]
I'll go ahead and rename +py.tests+ to +tests+ for convention. However, I am aware you can use classes for tests, but I am explicitly avoiding that, at the moment.

Thank you very much for your contributions, your interest, and time. :) You'll be seeing the rename in the next release. I'll close this issue once such has happened.

**Comment by lillian-lemmer** [comment]
I've made the update! https://github.com/lillian-lemmer/hypatia/commit/30834aad3eb1a0fc82117bd5ce1651562209e121
