### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by TeCoEd** [lillian-lemmer/hypatia#30]
Have you tried hypatia on a Raspberry Pi?, I was planning to give it ago over the weekend

**Comment by lillian-lemmer** [comment]
No I haven't. I'd love it if you gave that a go and let me know how it went! It'd be super keen if you included any special instructions or notes about software versions.

Thanks for showing interest in the project!

**Comment by TeCoEd** [comment]
Hi, it has been a while but I think I have got a working version on the Raspberry Pi.  I was using SSH so I need to wait until home to check the full graphic version, I will keep you updated.

**Comment by lillian-lemmer** [comment]
Closed, because you answered your own question! Would love to see your notes on installing on NetBSD. Note that the Installation Instructions, like the rest of the wiki, are public to editing. Thank you for your time and interest!
