### ISSUE TITLE
pygame for 64-bit Windows

### ISSUE THREAD

**Issue by chancyk** [lillian-lemmer/hypatia#32]
A compiled 64-bit Windows package for pygame can be found at:

http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame

Click the pygame‑1.9.2a0‑cp27‑none‑win_amd64.whl link to download the wheel file and then:

`pip install pygame‑1.9.2a0‑cp27‑none‑win_amd64.whl`

**Comment by lillian-lemmer** [comment]
I'll be sure to update the install guide in a bit. :)

**Comment by lillian-lemmer** [comment]
Updated! Checkout the wiki!
