### ISSUE TITLE
install-ubuntu-py27.sh contains a typo

### ISSUE THREAD

**Issue by jwl** [lillian-lemmer/hypatia#46]
Line 13 contains a typo. I'm still to new to pip so maybe I'm just doing something wrong, but it seems to me it should be changed from:

pip install --user -r requirements.txt .

to:

pip install --user -r requirements/python2.txt

I tried to run install-ubuntu-py27.sh from a fresh git clone this afternoon (July 5) and ran into an error when attempting to run the script. Changing the line to the above seemed to fix it for me.

**Comment by lillian-lemmer** [comment]
Thank you for pointing out this error. I have corrected the outdated scripts to point to the new requirements location in requirements/base.txt and others per install script.

https://github.com/lillian-lemmer/hypatia/commit/215ce51f308968b4370d7e71de048272a68216f6
