### ISSUE TITLE
Switch docs over to markdown

### ISSUE THREAD

**Issue by lillian-lemmer** [lillian-lemmer/hypatia#47]
Excluding docstring stuff. I want all of the wiki and readmes etc to be converted to markdown

**Comment by SanketDG** [comment]
Take a look at [mkdocs](https://github.com/mkdocs/mkdocs)

**Comment by ejmr** [comment]
I would also suggest [Pandoc](http://pandoc.org/) because it's more flexible in my opinion, especially  with regard to the types of output it can produce.  But it would require more work that mkdocs, so I don't think it's an easy call.  The comparative simplicity of mkdocs and its quality in general certainly makes it worth strong consideration.

**Comment by jwl** [comment]
I've gone and converted the [Project Guidelines](https://github.com/lillian-lemmer/hypatia/wiki/Project-Guidelines) page to Markdown since I was editing it anyway to flesh out the Testing section.

**Comment by jwl** [comment]
Converted [Nonprogrammer-Guide](https://github.com/lillian-lemmer/hypatia/wiki/Nonprogrammer-Guide), [Home](https://github.com/lillian-lemmer/hypatia/wiki) and [Profiles](https://github.com/lillian-lemmer/hypatia/wiki/Profiles) to Markdown and also updated them to reflect the current state of the project to the best of my knowledge.

**Comment by lillian-lemmer** [comment]
Thanks, @jwl! I appreciate it! Is that everything?

**Comment by jwl** [comment]
Just a few pages left:

* Walkabout-Sprites
* Tilesheets
* tilemap.txt
* Making Screen Recording Media

I'll be slowly making my way through them over the next day or so.

**Comment by jwl** [comment]
Converted [Walkabout-Sprites](https://github.com/lillian-lemmer/hypatia/wiki/Walkabout-Sprites), [Tilesheets](https://github.com/lillian-lemmer/hypatia/wiki/Tilesheets), [tilemap.txt](https://github.com/lillian-lemmer/hypatia/wiki/Tilesheets) and [Making-Screen-Recording-Media](https://github.com/lillian-lemmer/hypatia/wiki/Making-Screen-Recording-Media) from asciidoc to Markdown. As far as I'm aware, the entire wiki is now in Markdown.

**Comment by lillian-lemmer** [comment]
Thank you for your hard work, @jwl!
